-- Table: users
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table: finance_entries
CREATE TABLE IF NOT EXISTS finance_entries (
  id VARCHAR(255) PRIMARY KEY,
  fecha TIMESTAMP WITH TIME ZONE NOT NULL,
  tipo VARCHAR(255) NOT NULL,
  accion VARCHAR(255) NOT NULL,
  que VARCHAR(255) NOT NULL,
  plataforma_pago VARCHAR(255) NOT NULL,
  cantidad NUMERIC NOT NULL,
  detalle1 VARCHAR(255),
  detalle2 VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  user_id VARCHAR(255)
);

-- Table: recurring_records
CREATE TABLE IF NOT EXISTS recurring_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  amount NUMERIC NOT NULL,
  frequency VARCHAR(20) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  last_generated DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  plataforma_pago VARCHAR(50) NOT NULL DEFAULT 'any',
  accion VARCHAR(20) NOT NULL DEFAULT 'Gasto',
  tipo VARCHAR(100) NOT NULL DEFAULT '',
  detalle1 VARCHAR(255) NOT NULL DEFAULT '',
  detalle2 VARCHAR(255) NOT NULL DEFAULT '',
  dia SMALLINT NOT NULL DEFAULT 1,
  user_id VARCHAR(255)
);

